export const ADMIN_REQUEST ='[ADMIN_REQUEST]'
export const ADMIN_SUCCESS ='[ADMIN_SUCCESS]'
export const ADMIN_FAIL ='[ADMIN_FAIL]'

export const CREATE_ADMIN ='[CREATE_ADMIN]'
export const CREATE_book ='[CREATE_book]'
export const CHECK_ADMIN ='[CHECK_ADMIN]'
export const CREATEbook_DETS ='[CREATEbook_DETS]'
export const UPDATE_book ='[UPDATE_book]'
export const REMOVE_ADMIN ='[REMOVE_ADMIN]'
export const DELETEbook ='[DELETEbook]'
